# Generated by Django 2.2.1 on 2019-09-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[('Bhilai', 'Bhilai'), ('Durg', 'Durg')], max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='landmark',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
