# Generated by Django 2.2.1 on 2019-09-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190920_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pinCode',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
