# Generated by Django 2.2.1 on 2019-09-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pinCode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
