# Generated by Django 2.2.1 on 2019-09-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190922_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[('Bhilai', 'Bhilai'), ('Durg', 'Durg')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='landmark',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pinCode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
