# Generated by Django 2.2.1 on 2019-10-16 11:40

from django.db import migrations, models
import sell.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='year_of_book',
            field=models.SmallIntegerField(choices=[(2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=sell.models.current_year),
        ),
    ]
