# Generated by Django 2.2.1 on 2019-10-23 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20191016_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='original_price',
            new_name='price_toshow',
        ),
    ]
