# Generated by Django 2.2.1 on 2019-11-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_bestselling'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestselling',
            name='price',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='bestselling',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
