# Generated by Django 2.2.1 on 2019-11-03 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20191103_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestselling',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bestselling',
            name='stock',
        ),
    ]
