# Generated by Django 2.2.1 on 2019-09-27 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sell_order',
            old_name='sell_user',
            new_name='selling_user',
        ),
    ]
