# Generated by Django 2.2.1 on 2019-09-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_auto_20190927_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell_order',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='sell_order',
            name='city',
            field=models.CharField(blank=True, choices=[('Bhilai', 'Bhilai'), ('Durg', 'Durg')], max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='sell_order',
            name='landmark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sell_order',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='sell_order',
            name='pinCode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
