# Generated by Django 2.2.1 on 2019-09-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0003_auto_20190927_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell_order',
            name='date_recv',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sell_order',
            name='price',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
