# Generated by Django 2.2.1 on 2019-09-27 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0004_auto_20190927_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_order',
            name='selling_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
