# Generated by Django 2.2.1 on 2019-09-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0005_auto_20190927_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_order',
            name='address',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='sell_order',
            name='city',
            field=models.CharField(choices=[('Bhilai', 'Bhilai'), ('Durg', 'Durg')], max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='sell_order',
            name='landmark',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sell_order',
            name='number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sell_order',
            name='pinCode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
