# Generated by Django 2.2.1 on 2019-09-28 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0006_auto_20190927_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_order',
            name='city',
            field=models.CharField(choices=[('', '--choose please, its limited for now--'), ('Bhilai', 'Bhilai'), ('Durg', 'Durg')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='sell_order',
            name='number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sell_order',
            name='pinCode',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='theFirst.branch'),
        ),
    ]
