# Generated by Django 2.2.1 on 2019-09-28 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0007_auto_20190928_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theFirst.branch'),
        ),
    ]
