# Generated by Django 2.2.1 on 2019-10-16 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theFirst', '0008_auto_20190919_1642'),
        ('sell', '0008_auto_20190928_0937'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('branch', 'semester')},
        ),
    ]
