# Generated by Django 2.2.1 on 2019-09-17 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branches', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GoodDeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'I sem'), (2, 'II sem'), (3, 'III sem'), (4, 'IV sem'), (5, 'V sem'), (6, 'VI sem'), (7, 'VII sem'), (8, 'VIII sem')], default=1)),
                ('bookSets', models.BooleanField()),
                ('priceTosell', models.FloatField()),
                ('priceTOshow', models.FloatField()),
                ('description', models.CharField(max_length=1000, null=True)),
                ('TimeLimit', models.PositiveSmallIntegerField(default=2)),
                ('ImageUrl', models.URLField(unique=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theFirst.branch')),
            ],
        ),
        migrations.CreateModel(
            name='bestSelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'I sem'), (2, 'II sem'), (3, 'III sem'), (4, 'IV sem'), (5, 'V sem'), (6, 'VI sem'), (7, 'VII sem'), (8, 'VIII sem')], default=1)),
                ('bookName', models.CharField(max_length=120)),
                ('bookPrice', models.FloatField()),
                ('newedition', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theFirst.branch')),
            ],
        ),
    ]
