# Generated by Django 2.2.1 on 2019-09-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theFirst', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branches',
            field=models.CharField(max_length=100),
        ),
    ]
