# Generated by Django 2.2.1 on 2019-09-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theFirst', '0002_auto_20190917_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='gooddeals',
            name='InStock',
            field=models.BooleanField(default=True),
        ),
    ]
