# Generated by Django 2.2.1 on 2019-09-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theFirst', '0003_gooddeals_instock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestselling',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, 'sem I'), (2, 'sem II'), (3, 'sem III'), (4, 'sem IV'), (5, 'sem V'), (6, 'sem VI'), (7, 'sem VII'), (8, 'sem VIII')], default=1),
        ),
        migrations.AlterField(
            model_name='gooddeals',
            name='semester',
            field=models.CharField(choices=[(1, 'sem I'), (2, 'sem II'), (3, 'sem III'), (4, 'sem IV'), (5, 'sem V'), (6, 'sem VI'), (7, 'sem VII'), (8, 'sem VIII')], default=1, max_length=11),
        ),
    ]
