# Generated by Django 2.2.1 on 2019-09-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theFirst', '0006_auto_20190919_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestselling',
            name='semester',
            field=models.CharField(choices=[('I', 'sem I'), ('II', 'sem II'), ('III', 'sem III'), ('IV', 'sem IV'), ('V', 'sem V'), ('VI', 'sem VI'), ('VII', 'sem VII'), ('VIII', 'sem VIII')], default='I', max_length=11),
        ),
        migrations.AlterField(
            model_name='gooddeals',
            name='semester',
            field=models.CharField(choices=[('I', 'sem I'), ('II', 'sem II'), ('III', 'sem III'), ('IV', 'sem IV'), ('V', 'sem V'), ('VI', 'sem VI'), ('VII', 'sem VII'), ('VIII', 'sem VIII')], default='I', max_length=11),
        ),
    ]
