# Generated by Django 2.2.1 on 2019-09-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theFirst', '0007_auto_20190919_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestselling',
            name='InStock',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gooddeals',
            name='InStock',
            field=models.SmallIntegerField(default=1),
        ),
    ]
