# Generated by Django 2.2.1 on 2019-10-25 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theFirst', '0008_auto_20190919_1642'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bestSelling',
        ),
    ]
