# Generated by Django 2.2.1 on 2019-11-03 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theFirst', '0009_delete_bestselling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gooddeals',
            name='TimeLimit',
        ),
    ]
