# Generated by Django 2.2.1 on 2019-11-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theFirst', '0010_remove_gooddeals_timelimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='gooddeals',
            name='showing',
            field=models.BooleanField(default=True),
        ),
    ]
