# Generated by Django 2.2.1 on 2019-11-03 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theFirst', '0011_gooddeals_showing'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_deals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=1000)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theFirst.GoodDeals')),
            ],
        ),
    ]
