# Generated by Django 2.2.1 on 2019-11-03 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theFirst', '0010_remove_gooddeals_timelimit'),
        ('cart', '0006_orderitem_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='good_deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theFirst.GoodDeals'),
        ),
    ]
