# Generated by Django 2.2.1 on 2019-11-03 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_orderitem_good_deal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='good_deal',
        ),
    ]
